@base_url = localhost:3333
@token = {{CreateSession.response.body.token}}

# @name CreateSession
POST http://{{base_url}}/sessions
content-type: application/json

{
    "email": "fulano@mail.com",
    "password": "654321"
}

###

# @name ListUsers
GET http://{{base_url}}/users
Authorization: Bearer {{token}}

###

# @name CreateUser
POST http://{{base_url}}/users
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "sarah",
    "email": "sarah@mail.com",
    "password": "123456"
}

###

# @name UpdateAvatar
PATCH http://{{base_url}}/users/avatar
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="my-avatar.png"
Content-Type: image/png

< ./avatar-sample.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

@product_id = {{CreateProduct.response.body.id}}

# @name CreateProduct
POST http://{{base_url}}/products
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Book A",
    "price": 19.90,
    "quantity": 50
}

###

# @name UpdateProduct
PUT http://{{base_url}}/products/{{product_id}}
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Book Ax",
    "price": 19.90,
    "quantity": 50
}

###

# @name ShowProduct
GET http://{{base_url}}/products/{{product_id}}
Authorization: Bearer {{token}}

###

# @name ListProducts
GET http://{{base_url}}/products
Authorization: Bearer {{token}}

###

# @name DeleteProduct
DELETE  http://{{base_url}}/products/{{product_id}}
Authorization: Bearer {{token}}

###

@costumer_id = {{CreateCostumer.response.body.id}}

# @name CreateCostumer
POST http://{{base_url}}/costumers
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Cliente Bom",
    "email": "cliente.bom@xpto.com"
}

###

# @name UpdateCostumer
PUT http://{{base_url}}/costumers/{{costumer_id}}
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Cliente Muito Bom",
    "email": "cliente.bom@xpto.com"
}

###

# @name ShowCostumer
GET http://{{base_url}}/costumers/{{costumer_id}}
Authorization: Bearer {{token}}

###

# @name ListCostumers
GET http://{{base_url}}/costumers
Authorization: Bearer {{token}}

###

# @name DeleteCostumer
DELETE  http://{{base_url}}/costumers/{{costumer_id}}
Authorization: Bearer {{token}}

###

# @name ForgotPassword
POST http://{{base_url}}/password/forgot
content-type: application/json

{
    "email": "fulano@mail.com"
}

###

# @name ResetPassword
POST http://{{base_url}}/password/reset
content-type: application/json

{
  "token": "5fd4f74a-25f5-4b39-804d-9eeb5b1c5db6",
  "password": "654321",
  "passwordConfirmation": "654321"
}

###

# @name ShowProfile
GET http://{{base_url}}/profile
Authorization: Bearer {{token}}

###

# @name UpdateProfile
PUT http://{{base_url}}/profile
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Fulano da Silva",
    "email": "fulano.silva@mail.com",
    "password": "acbdef",
    "password_confirmation": "acbdef",
    "old_password": "acbdef"
}

###

@order_id = {{CreateOrder.response.body.id}}

# @name CreateOrder
POST http://{{base_url}}/orders
Authorization: Bearer {{token}}
content-type: application/json

{
    "costumer_id": "9fdedbf0-874d-4e0e-8c1d-bcb73fce1430",
    "products": [
        {
            "id": "38e96345-0d8d-4732-9314-bf94472d939f",
            "quantity": 1
        },
        {
            "id": "bb5ed1a4-5b15-44fe-ad5c-d65c9a855c7c",
            "quantity": 10
        }
    ]
}

###

# @name ShowOrder
GET http://{{base_url}}/orders/{{order_id}}
Authorization: Bearer {{token}}

###
